### ISSUE TITLE
Missing Java libraries?

### ISSUE THREAD

**Issue by AQLT** [palatej/rjd3toolkit#11]
Are some Java libraries missing? Lots of .jar files were removed (also in rjd3x13 and rjd3tramoseats): is it normal or they will soon be updated? It doesn't seem to work for the moment (`java.lang.ClassNotFoundException`).

**Comment by palatej** [comment]
I aligned the new R packages with the new java libraries (huge refactoring/renaming for the release of JD+ 3.0). Check that you are using the right libraries and cleanup your projects to avoid (hidden) references to the old jar. I will create new releases on github

**Comment by palatej** [comment]
Except for some minor adaptations, this is the last modification before the release of version 3

**Comment by palatej** [comment]
See the projects jdplus_main, jdplus_incubator, jdplus_experimental... for the new organization of the java libraries (no longer jdemetra_core/jdemetra_app)

**Comment by AQLT** [comment]
So it is that in rjd3toolkit now you only have the [protobuf-java-3.21.6.jar](https://github.com/palatej/rjd3toolkit/blob/main/inst/java/protobuf-java-3.21.6.jar) file and no more the other files (toolkit, sa, etc.)? I will check it again.

**Comment by palatej** [comment]
No, you have more or less the same jars, but with different (normalized) names

**Comment by palatej** [comment]
The libraries were not taken into account. It is corrected now
