### ISSUE TITLE
cannot use First, Last, Excluding in "set_basic" function

### ISSUE THREAD

**Issue by annasmyk** [palatej/rjd3toolkit#15]
cannot use First, Last, Excluding in "set_basic" function
("From", "To", "Between" work well)

example

spec_x13_d<-rjd3x13::spec_x13("rsa5c")
spec_x13_d<-set_basic(spec_x13_d,Type="First", n0 = 60,
                      preliminary.check = TRUE,
                      preprocessing= TRUE)
Returns

Error in set_basic(spec_x13_d, Type = "First", n0 = 60, preliminary.check = TRUE,  : 
  unused argument (Type = "First")

Same return with Last and Excluding

**Comment by AQLT** [comment]
Did you try with `type` instead of `Type`?

**Comment by annasmyk** [comment]
well it works indeed !
