### ISSUE TITLE
in set_basic: preprocessing = superfluous parameter ?

### ISSUE THREAD

**Issue by annasmyk** [palatej/rjd3toolkit#16]
in set_basic: preprocessing MUST be TRUE, otherwise no estimation at all (and NOT just a deactivation of the pre-processing step as currently described)

better to make this parameter unavailable ?

example

spec_x13_d<-rjd3x13::spec_x13("rsa5c")
spec_x13_d<-set_basic(spec_x13_d, preprocessing= FALSE)

sa_x13_d<- rjd3x13::x13(y_raw, spec_x13_d)

returns: 

Error in .jcall("jdplus/x13/base/r/X13", "[B", "toBuffer", jq) :
    java.lang.NullPointerException: Cannot 
 invoke "jdplus.toolkit.base.core.modelling.GeneralLinearModel.getDescription()" 
 because "model" is null

**Comment by palatej** [comment]
I prefer to keep it: it could be used with other algorithms, like STL. The code for X13 and the output in R should be adapted for that special case (not a priority)

**Comment by annasmyk** [comment]
parameter deactivated in rjd3x13
