### ISSUE TITLE
cannot use First, Last, excluding in set_estimate

### ISSUE THREAD

**Issue by annasmyk** [palatej/rjd3toolkit#17]
same problem as with set basic 

example 
spec_x13_d<-rjd3x13::spec_x13("rsa5c")
spec_x13_d<-set_estimate(spec_x13_d,Type="Last", n1 = 60)

returns 

Error in set_estimate(spec_x13_d, Type = "Last", n1 = 60) : 
  unused argument (Type = "Last")

**Comment by AQLT** [comment]
same as in #15, you should use `type = "Last"` and not `Type = "Last"`.

**Comment by annasmyk** [comment]
it works , sorry for the typo
