### ISSUE TITLE
Bug in testupdownruns

### ISSUE THREAD

**Issue by carlos-saez** [palatej/rjd3toolkit#3]
When I try to call the testupdownruns function it returns the following error:

Error in .jcall("demetra/stats/r/Tests", "Ldemetra/stats/StatisticalTest;",  : 
  method testOfUpDownsRuns with signature ([DZ)Ldemetra/stats/StatisticalTest; not found

I think this might be caused by an extra s in Downs in the Java call, while the relevant Java method seems to be testOfUpDownRuns.

**Comment by palatej** [comment]
You are right. Thanks. 
I correct it immediatly.

**Comment by palatej** [comment]
Most of the R routines (which are just wrappers around the Java code) have not been seriously tested. We should create unit tests or - at least - add examples in the documentation to check them automatically.
Don't hesitate to propose some modifications in the code.
Thanks again.
