### ISSUE TITLE
Estimation doesn't work with new .jar

### ISSUE THREAD

**Issue by TanguyBarthelemy** [palatej/rjd3toolkit#31]
Since last commit of **rjd3toolkit**, estimation with **x13** and **tramoseats** doesn't work anymore.

For example : 
```
rjd3toolkit::ABS[, 1] |> rjd3x13::x13()
```
```
Error in .jcall("jdplus/toolkit/base/r/timeseries/TsUtility", "Ljdplus/toolkit/base/api/timeseries/TsData;",  : 
  java.util.ServiceConfigurationError: jdplus.toolkit.base.api.information.InformationExtractor: Provider jdplus.x13.base.core.x13.extractors.X13DiagnosticsExtractor could not be instantiated
```

And same error with `rjd3toolkit::ABS[, 1] |> rjd3tramoseats::tramo()`

**Comment by AQLT** [comment]
it comes from the fact that the file` inst/java/jdplus-sa-base-api-3.0.0.jar` was (I think accidentally) removed from the last commit.
