### ISSUE TITLE
Easter February long-term mean 

### ISSUE THREAD

**Issue by AQLT** [palatej/rjd3toolkit#8]
Should the month of February be corrected from long-term mean? Currently only March/April are corrected but in some cases, the long-term mean of February is not null. For example, with `duration = 25` the long-term pre-computed mean is 0.003680 for February, 0.657600 for March and 0.338720 for April:
``` r
library(rjd3toolkit)
s = ts(1, start = 1990, end = c(1990,4), frequency = 12)
none <- easter_variable(s = s,
                duration = 25, correction = "None", endpos = -1) 
lgmean <- easter_variable(s = s,
                          duration = 25, correction = "PreComputed", endpos = -1)
none - lgmean
#>          Jan     Feb     Mar     Apr
#> 1990 0.00000 0.00000 0.65760 0.33872
```

**Comment by palatej** [comment]
You are right, but a duration of 25 days doesn't make sense. I limit it now to 20 days to avoid this kind of (meaningless) problem.
(control implemented in the next release).
