### ISSUE TITLE
 object 'r2p_ts' is not exported by 'namespace:rjd3toolkit'

### ISSUE THREAD

**Issue by hufeide** [palatej/rjd3toolkit#9]
when i install package using remotes::install_github("palatej/rjd3modelling"),it raised error like object 'r2p_ts' is not exported by 'namespace:rjd3toolkit'.

**Comment by AQLT** [comment]
rjd3toolkit now replaces rjd3modelling, rj3sa and rjd3arima: you no longer need those packages.

**Comment by hufeide** [comment]
Thanks,I'll try.
